HOST: http://analytics.tnt-ea.com

--- Analytics ---

---
TNT Analytics Service API
---

--
Version Resource
--

GET /rest/version
> Content-Type: application/json
< 200
{
    "serviceId": "analytics-frontend",
    "serviceVersion": "0.0.1",
    "environment": "integration",
    "apiVersions": "v1"
}

-- 
Event Resource
Resource for use in tracking events
--

Track an event.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "logged-in"
    }
}
< 201

Track an event with a timestamp.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "logged-in",
        "properties": {
            "timestamp": "2013-11-11T13:24:587Z"
        }
    }
}
< 201

Track an event with a user id.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "logged-in,
        "properties": {
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        }
    }
}
< 201

Track an event with custom properties.  Custom properties can be any of the following: strings, integers, decimal numbers, timestamps.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "logged-in",
        "properties": {
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
            "timestamp": "2013-11-11T13:24:587Z"
            "customString": "something",
            "customTimestamp": "2013-11-11T13:24:587Z",
            "customDecimal": 2.5,
            "customInteger": 5
        }
    }
}
< 201

-- 
Event Log Resources 
Resources for use in tracking events
--

Track an event log.

POST /rest/v1/games/:gameId/eventlog
> Content-Type: application/json
{
    "events": [
        {
            "name": "logged-in",
            "properties": {
                "timestamp": "2013-11-11T13:24:587Z"
            }
        },
        {
            "name": "logged-in",
            "properties": {
                "timestamp": "2013-11-11T13:25:587Z"
            }
        }
    ]
}
< 201

--
Tracking Ad Events

Below are some examples of sending ad events to the TNT Analytics Service.  Ad events are just regular events, 
sent to the `events` or `eventlog` endpoints listed above, but conform to a certain format.

To track ad events, some particular fields should be included to allow for thorough reporting.  These include:

* `name` - The name of the event (See below for possible values)
* `properties.timestamp` - The timestamp (full date and time stamp in ISO 8601 format) that the event happened
* `properties.userId` - The id of the user.  This can be any unique identifier for the user (tntId is recommended if available). Please ensure you are sending a consistent user id for the same user to ensure valid reports.
* `properties.type` - The type of ad (See below for possible values)
* `properties.provider` - The provider of the ad (See below for possible values)

# Name
The `name` field must have one of the following values:

* `ad-request` - An ad was requested from the ad provider
* `ad-request-success` - An ad was successfully recieved from the ad provider
* `ad-request-fail` - An ad was not successfully recieved from the ad provider
* `ad-clicked` - An ad was clicked by a user

# Type
The `properties.type` field can have any of the following values:

* `banner` - Type of ad was a banner ad
* `interstitial` - Type of ad was an interstitial ad
* `offerwall` - Type of ad was an offer wall

**Note**: Arbitrary ad types are supported by the `properties.type` 
field if none of the above listed types apply.

# Provider
The `properties.provider` field can have any of the following values:

* `google` - Ad provider was Google (AdMob)
* `burstly` - Ad provider was Burstly

**Note**: Arbitrary ad providers are supported by the `properties.provider` 
field if none of the above listed providers apply.

# Examples

--

Ad Requested

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "ad-requested",
        "properties": {
            "timestamp": "2013-11-11T13:25:587Z",
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
            "type": "banner",
            "provider": "google"
        }
    }
}
< 201

Ad Shown

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "ad-shown",
        "properties": {
            "timestamp": "2013-11-11T13:25:587Z",
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
            "type": "banner",
            "provider": "google"
        }
    }
}
< 201

Ad Clicked

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "ad-clicked",
        "properties": {
            "timestamp": "2013-11-11T13:25:587Z",
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
            "type": "banner",
            "provider": "google"
        }
    }
}
< 201