HOST: http://analytics.tnt-ea.com

--- Analytics ---

---
TNT Analytics Service API
---

-- 
Version Resource
--

GET /rest/version
> Content-Type: application/json
< 200
{
    "serviceName": "analytics-service",
    "serviceVersion": "1.0.0",
    "apiVersion": "v1"
}

-- 
Event Resources 
Resources for use in tracking events
--

Track an event.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "ad-shown"
    }
}
< 201

Track an event with a timestamp.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "ad-shown",
        "properties": {
            "timestamp": "2013-11-11T13:24:587Z"
        }
    }
}
< 201

Track an event with a user id.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "Logged In,
        "properties": {
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        }
    }
}
< 201

Track an event with custom properties.  Custom properties can be any of the following: strings, integers, decimal numbers, timestamps.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
    "event": {
        "name": "Some Custom Event",
        "properties": {
            "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
            "timestamp": "2013-11-11T13:24:587Z"
            "customString": "something",
            "customTimestamp": "2013-11-11T13:24:587Z",
            "customDecimal": 2.5,
            "customInteger": 5
        }
    }
}
< 201

-- 
Event Log Resources 
Resources for use in tracking events
--

Track an event log.

POST /rest/v1/games/:gameId/eventlog
> Content-Type: application/json
{
    "events": [
        {
            "name": "ad-shown",
            "properties": {
                "timestamp": "2013-11-11T13:24:587Z"
            }
        },
        {
            "name": "ad-clicked",
            "properties": {
                "timestamp": "2013-11-11T13:25:587Z"
            }
        }
    ]
}
< 201