HOST: http://analytics.tnt-ea.com

--- Analytics ---

---
TNT Analytics Service API
---

--
Version Resource
--

GET /rest/version
> Content-Type: application/json
< 200
{
    "serviceId": "analytics-frontend",
    "serviceVersion": "0.0.1",
    "environment": "integration",
    "apiVersions": "v1"
}

-- 
Event Resource

Resource for use in tracking events

# Field: Name

* Field: `name`
* Type: String
* Required: Yes

**Note:** If this field is not specified in the request, the event will be considered in an **error** state.
Events in an error state will be published to the error output location, and not available in any reports.

# Field: User Id

* Field: `parameters.userId`
* Type: String
* Required: Yes

**Note:** If this field is not specified in the request, the event will be considered in an **error** state.
Events in an error state will be published to the error output location, and not available in any reports.


# Field: Platform

* Field: `parameters.platform`
* Type: String
* Required: Yes

The `parameters.platform` field can have any of the following values:

* `apple` - If the user is playing on an Apple device
* `google` - If the user is playing on a Google device
* `amazon` - If the user is playing on an Amazon device

**Note**: If none of the above platforms are specified, the platform will be specified as `unknown`.
In this case the event will be considered in an error state, and will be published to the error output location and will not be available in any reports.

# Field: Session Id

* Field: `parameters.sessionId`
* Type: String
* Required: Yes

**Note:** If this field is not specified in the request, the event will be considered in an **error** state.
Events in an error state will be published to the error output location, and not available in any reports.

# Field: Type

* Field: `parameters.type`
* Type: String
* Required: Yes

The `parameters.type` field can have any of the following values:

* `tnt` - For events whose format is specified by TNT in this document.
* `custom` - For custom events.

**Note**: If none of the above types are specified, the platform will be specified as `unknown`.
In this case the event will be published to the unknown type output location and will not be available in any reports.

# Field: Timestamp

* Field: `parameters.timestamp`
* Type: Long (milliseconds since epoch)
* Required: No

**Note**: If a timestamp is not specified, the server will fill in this field with the current server time.
It is recommended to send your own timestamp, to ensure accurracy of reports.

# Field: TNT Id

* Field: `parameters.tntId`
* Type: String
* Required: No

**Note**: Though not required, it is recommended to send a TNT Id in your request (if available).
Sending a TNT Id will allow for cross service querying and reporting.

--

Track an event.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "log-in",
      "parameters": {
        "userId": "1234",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386105886413
    }
  }
}
< 201

Track an event with custom parameters.  Custom parameters can be any of the following: strings, integers, decimal numbers, timestamps.

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "log-in",
      "parameters": {
        "userId": "1234",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386105886413
        "customString": "something",
        "customTimestamp": "2013-11-11T13:24:587Z",
        "customDecimal": 2.5,
        "customInteger": 5
    }
  }
}
< 201

-- 
Event Log Resources 
Resources for use in tracking events
--

Track an event log.

POST /rest/v1/games/:gameId/eventlog
> Content-Type: application/json
{
    "events": [
        {
            "name": "log-in",
            "parameters": {
                "userId": "1234",
                "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
                "platform":"apple",
                "sessionId":"1234567890",
                "type":"tnt",
                "timestamp": 1386105886413
        },
        {
            "name": "log-out",
            "parameters": {
                "userId": "1234",
                "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
                "platform":"apple",
                "sessionId":"1234567890",
                "type":"tnt",
                "timestamp": 1386105886413
        }
    ]
}
< 201

--
Analytics API Responses
--

--
Tracking Ad Events

Below are some examples of sending ad events to the TNT Analytics Service.  Ad events are just regular events, 
sent to the `events` or `eventlog` endpoints listed above, but conform to a certain format.

**Note**: Ad events must also conform to the documentation for the `events` endpoint listed above.

# Field: Name

To be considered an ad event, the `name` field must have one of the following values:

* `ad-requested` - An ad was requested from the ad provider
* `ad-request-failed` - An ad was not recieved from the ad provider (if an ad was not available, or the provider returned an exception)
* `ad-shown` - An ad was shown to the user
* `ad-action-completed` - An ad action was competed by the user (ie. banner ad clicked, offerwall offer completed etc.)

To track ad events, some additional fields should be included:

* `parameters.adType` - The type of ad (See below for possible values)
* `parameters.adProvider` - The provider of the ad (See below for possible values)

# Field: Ad Type

* Field: `parameters.adType`
* Type: String
* Required: Yes

The `parameters.adType` field can have any of the following values:

* `banner` - Type of ad was a banner ad
* `interstitial` - Type of ad was an interstitial ad
* `offerwall` - Type of ad was an offer wall

**Note:** If this field is not specified in the request, the event will be considered in an **error** state.
Events in an error state will be published to the error output location, and not available in any reports.

# Field: Ad Provider

* Field: `parameters.adProvider`
* Type: String
* Required: Yes

**Note:** If this field is not specified in the request, the event will be considered in an **error** state.
Events in an error state will be published to the error output location, and not available in any reports. 

The `parameters.adProvider` field can have any of the following values:

* `admob` - Ad provider was AdMob
* `burstly` - Ad provider was Burstly

# Additional Fields

Some additional fields are supported based on which Ad Provider is specified:

If the Ad Provider is `admob`, the following additional fields are supported:

* `parameters.adPublisherId` - The AdMob publisher id

If the Ad Provider is `burstly`, the following additional fields are supported:

* `parameters.adAppId` - The Burstly App Id
* `parameters.adZoneId` - The Burstly Zone Id

If the Ad Provider is `burstly` and the Ad Type is `offerwall` or `ea2`, 
the following additional fields are supported:

* `parameters.adCurrencyId` - The in-game currency id given to the user (if an offer was completed)
* `parameters.adCurrencyAmount` - The amount of in-game currency awarded to the user (if an offer was completed)

# Examples

--

Ad Requested (Burstly)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-requested",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "banner",
        "adAppId": "1234",
        "adZoneId": "2345"
    }
  }
}
< 202

Ad Requested (AdMob)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-requested",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "admob",
        "adType": "banner",
        "adPublisherId": "0987654321"
    }
  }
}
< 202

Ad Request Failed (Burstly)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-request-failed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "banner",
        "adAppId": "1234",
        "adZoneId": "2345"
    }
  }
}
< 202

Ad Request Failed (AdMob)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-request-failed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "admob",
        "adType": "banner",
        "adPublisherId": "0987654321"
    }
  }
}
< 202

Ad Shown (Burstly)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-shown",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "banner",
        "adAppId": "1234",
        "adZoneId": "2345"
    }
  }
}
< 202

Ad Shown (AdMob)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-shown",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "admob",
        "adType": "banner",
        "adPublisherId": "0987654321"
    }
  }
}
< 202

Ad Action Completed (Burstly)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-action-completed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "banner",
        "adAppId": "1234",
        "adZoneId": "2345"
    }
  }
}
< 202

Ad Action Completed (AdMob)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-action-completed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "admob",
        "adType": "banner",
        "adPublisherId": "0987654321"
    }
  }
}
< 202

Ad Action Completed (Burstly Offerwall)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-action-completed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "offerwall",
        "adAppId": "1234",
        "adZoneId": "2345",
        "adCurrencyId": "coins",
        "adCurrencyAmount": 50
    }
  }
}
< 202

Ad Action Completed (Burstly EA2)

POST /rest/v1/games/:gameId/events
> Content-Type: application/json
{
  "event": 
    {
      "name": "ad-action-completed",
      "parameters": {
        "userId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "tntId": "2501b552-a469-4e04-93b1-1e3c34523d85",
        "platform":"apple",
        "sessionId":"1234567890",
        "type":"tnt",
        "timestamp": 1386168467403,
        "adProvider": "burstly",
        "adType": "ea2",
        "adAppId": "1234",
        "adZoneId": "2345",
        "adCurrencyId": "coins",
        "adCurrencyAmount": 50
    }
  }
}
< 202